### ISSUE TITLE
windows installation

### ISSUE THREAD

**Issue by jeffythedragonslayer** [sp1187/n64triangle#1]
Is there a mips64-elf toolchain on windows that can be used?  The compilation instructions look like they are geared toward linux.

**Comment by sp1187** [comment]
I have personally only tried on Linux, but for Windows I recommend following the [libdragon](https://github.com/DragonMinded/libdragon) instructions. You might also get it to work by using WSL and building the toolchain like you would on Linux. I will probably not add any additional Windows-specific support in the makefiles as it's not common on libdragon projects.
